version: '3.8'

services:
  frontend:
    build: 
      context: ./ 
    ports:
      - "5173:5173"
    expose:
      - "5173"                
    environment:
      - NODE_ENV=production     
    volumes:
      - ./frontend:/usr/share/nginx/html