version: '3.8'

services:
  backend:
    build:
      context: ./ 
    ports:
      - "3000:3000"     
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app